name: Build Java app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Debug
        run: ls -lrt
  build-maven:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ./java-app
    steps:
      - name: Debug
        run: ls -lrt
      - name: setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
#      - name: Debug effective POM
#        run: mvn help:effective-pom
      - name: Test Report (mikepenz)
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - name: Test Report (dorny)
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: Java Tests            # Name of the check run which will be created
          path: '**/target/surefire-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit        # Format of test results
  build-nodejs:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ./angular-app
    steps:
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    - run: npm run build --if-present
  upload-artifact:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - build-maven
      - build-nodejs
    defaults:
      run:
        working-directory: ./angular-app
    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifact
          path: ./java-app/target/*.jar
      - name: deploy artifact
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
