name: Build Java app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout-build-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: List target directory
        run: ls target
      - name: Test Report (mikepenz)
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - name: Test Report (dorny)
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: Java Tests            # Name of the check run which will be created
          path: '**/target/surefire-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit        # Format of test results
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar
      - name: deploy artifact
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
